version: 2

sources:
  - name: staging
    database: invertible-lens-447717-d5
    schema: dataset_8c1e2b66653d894e2c51ac8d4be89778
    tables:
      - name: ext_green_taxi
      - name: ext_yellow_taxi
      - name: ext_fhv_taxi
